# -*- coding: utf-8 -*-
"""
RAG 接口主流程回归场景 (RAG-001~057, 共 57 条)  数据来源: 知识库平台-主流程回归测试用例.xlsx
由 tools/gen_rag_mainflow_scenarios.py 生成, 勿手改; 需重新生成请运行该脚本。
每条用例携带 Excel 前置条件/操作步骤/预期(note) 与已验证的真实接口步骤(steps)。
"""
from pathlib import Path

THIS_DIR = Path(__file__).parent
SCENARIOS = {
    'RAG-001': {
        'title': '首次登录自动加入公共工作空间',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已注册企业邮箱账号 2. 未加入任何工作空间 | Excel步骤: 1. 浏览器访问知识库平台 2. 输入企业邮箱 3. 输入初始密码 bssoft@123 4. 点击登录 | 预期: 登录成功；自动拉入公共工作空间；可看到平台功能菜单',
        'steps': [{'method': 'POST', 'path': '/api/v1/user/login', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'email': '${EMAIL}', 'password': '${PASSWORD}'}, 'desc': '邮箱密码登录'}],
    },
    'RAG-002': {
        'title': '搜索工作空间',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已登录知识库平台 2. 已在公共空间 | Excel步骤: 1. 快速入门页点击 STEP1.加入工作空间 2. 点击「搜索工作空间」按钮 3. 弹出搜索工作空间弹窗 4. 输入工作空间名称（如 财务部） 5. 点击搜索 | 预期: 显示匹配的工作空间列表',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '登录后工作空间数据可达'}],
    },
    'RAG-003': {
        'title': '申请加入已有工作空间',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'MIX',
        'note': '前置: 1. 搜索结果中已显示目标工作空间 | Excel步骤: 1. 选择工作空间 2. 点击「申请加入」 3. 提交申请 | 预期: 申请提交成功；显示待审批状态；工作空间管理员收到通知',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '空间数据可达(申请入口)'}],
    },
    'RAG-004': {
        'title': '工作空间管理员审批加入申请',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'MIX',
        'note': '前置: 1. 管理员账号 2. 收到待审批申请 | Excel步骤: 1. 进入个人中心-设置-成员 2. 查看已提交未处理的申请列表 3. 选择申请人 4. 点击同意 | 预期: 申请人加入工作空间成功；申请人收到通知；新成员出现在成员列表',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '成员数据可达(审批前置)'}],
    },
    'RAG-005': {
        'title': '切换工作空间',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 用户在多个工作空间（含公共空间 + 至少 1 个已加入） | Excel步骤: 1. 点击左侧菜单栏顶部当前工作空间名称 2. 弹出工作空间切换弹窗 3. 选择需要前往的工作空间 4. 点击切换 | 预期: 成功切换到目标工作空间；左侧菜单内容更新；用户继续使用平台功能',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '切换后数据可达'}],
    },
    'RAG-006': {
        'title': '查看当前工作空间成员',
        'module': '加入工作空间',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'MIX',
        'note': '前置: 1. 已加入工作空间 | Excel步骤: 1. 进入个人中心-设置-成员 2. 查看成员列表 | 预期: 展示全部成员（姓名/邮箱/角色/加入时间）；可按角色筛选',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '成员列表(同空间数据)'}],
    },
    'RAG-007': {
        'title': '查看工作空间信息',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'MIX',
        'note': '前置: 1. 已加入工作空间 | Excel步骤: 1. 点击左侧菜单栏顶部工作空间名称 2. 在弹出框点击查看详情 | 预期: 展示工作空间基础信息（名称/创建人/创建时间/成员数/简介/管理员列表）',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '空间信息数据可达'}],
    },
    'RAG-008': {
        'title': '工作空间-申请创建新工作空间',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'UI',
        'note': '前置: 1. 当前账号无任何工作空间 | Excel步骤: 1. 在加入工作空间页点击「申请创建新工作空间」 2. 填写申请表单（工作空间名称 + 用途说明） 3. 提交申请 | 预期: 申请提交成功；邮件审批流启动；审批通过后自动创建空间并初始化',
        'steps': [],
    },
    'RAG-009': {
        'title': '工作空间-退出工作空间',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'MIX',
        'note': '前置: 1. 用户在多个工作空间 | Excel步骤: 1. 进入个人中心-设置-成员 2. 选择工作空间 3. 点击退出 4. 二次确认 | 预期: 成功退出该工作空间；该工作空间从切换列表移除；保留其他工作空间权限',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '退出前数据可达'}],
    },
    'RAG-010': {
        'title': '工作空间-修改个人信息',
        'module': '加入工作空间',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'UI',
        'note': '前置: 1. 已加入工作空间 | Excel步骤: 1. 进入个人中心-设置-个人信息 2. 修改姓名/电话/头像等 3. 保存 | 预期: 信息修改生效；其他成员可见更新后的信息',
        'steps': [],
    },
    'RAG-011': {
        'title': '查看工作空间知识库列表',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已加入工作空间 2. 工作空间有知识库 | Excel步骤: 1. 点击左侧「知识库」按钮 2. 查看知识库列表 | 预期: 展示工作空间成员创建的所有知识库（卡片/列表形式）；含名称、创建人、创建时间、统计',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '知识库列表'}],
    },
    'RAG-012': {
        'title': '创建知识库-基础创建',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已加入工作空间 | Excel步骤: 1. 知识库列表页点击右上角「+知识库」按钮 2. 填写知识库名称（如 财务制度库） 3. 选择嵌入模型 4. 点击确定 | 预期: 知识库创建成功；进入知识库详情页；可继续配置切片与检索策略',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'name': '回归知识库', 'embedding_model': '${EMBEDDING_MODEL}'}, 'desc': '创建知识库'}],
    },
    'RAG-013': {
        'title': '配置知识库-切片方法',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建知识库 2. 上传文档前 | Excel步骤: 1. 进入知识库详情 2. 点击「配置」 3. 进入「切片方法」页 4. 选择切片策略（如通用模式/QA模式/父子切片等） 5. 设置切片参数 6. 保存 | 预期: 切片策略保存成功；上传文档时按此策略解析',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'naive'}, 'desc': '配置切片方法'}],
    },
    'RAG-014': {
        'title': '配置知识库-检索策略（基础）',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建知识库 | Excel步骤: 1. 进入「检索策略」页 2. 设置相似度阈值 3. 设置 Top-K 4. 设置混合检索权重（向量+全文） 5. 设置 rerank 模型 6. 保存 | 预期: 检索策略保存成功；知识库检索时按此配置执行',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'top_k': 10, 'threshold': 0.2, 'rerank_id': 'default'}}, 'desc': '配置检索策略'}],
    },
    'RAG-015': {
        'title': '配置知识库-多路召回策略',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索策略页 | Excel步骤: 1. 开启多路召回开关 2. 选择召回路径：分片内容/分片标题/关键词/问题 3. 设置各路权重 4. 保存 | 预期: 多路召回配置生效；检索时按多路加权排序',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'search_method': 'hybrid'}}, 'desc': '多路召回配置'}],
    },
    'RAG-016': {
        'title': '配置知识库-切片方法高级配置',
        'module': '查看/创建知识库',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法页 | Excel步骤: 1. 展开高级配置 2. 开启关键词提取 3. 开启问题提取 4. 保存 | 预期: 高级配置生效；按需提取关键词/问题用于召回',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'naive', 'parser_config': {'auto_keywords': True}}, 'desc': '高级切片配置'}],
    },
    'RAG-017': {
        'title': '配置知识库-QA 模式',
        'module': '查看/创建知识库',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法页 | Excel步骤: 1. 切片模式选 QA 模式 2. 确认 Question 存于问题路 3. 确认 Answer 存于分片内容 4. 开启多路召回并切换到基于问题路 5. 保存 | 预期: QA 模式配置生效；检索时按问题匹配答案',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'qa'}, 'desc': 'QA切片模式配置'}],
    },
    'RAG-018': {
        'title': '上传知识文件-单文件拖拽',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识文件列表页 | Excel步骤: 1. 点击右上角「新增文件」 2. 拖入 1 个文件（如 test.txt） 3. 上传完成 | 预期: 文件上传成功；出现在文件列表；初始解析状态为「未开始」',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'file_type': 'txt', 'file': '回归测试文件.txt'}, 'desc': '上传单文件'}],
    },
    'RAG-019': {
        'title': '上传知识文件-多文件批量上传',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识文件列表页 | Excel步骤: 1. 点击「新增文件」 2. 一次性拖入多个文件 3. 全部上传完成 | 预期: 所有文件上传成功；按上传顺序出现在文件列表',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'files': ['回归测试文件1.txt', '回归测试文件2.txt']}, 'desc': '批量上传'}],
    },
    'RAG-020': {
        'title': '上传支持格式验证（word/pdf/excel/ppt/txt）',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识文件列表页 | Excel步骤: 1. 依次上传 docx / pdf / xlsx / pptx / txt 各 1 个文件 | 预期: 所有格式支持上传；出现在文件列表',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'files': ['test.docx', 'test.pdf', 'test.xlsx', 'test.pptx', 'test.txt']}, 'desc': '多格式上传'}],
    },
    'RAG-021': {
        'title': '知识文件-触发解析',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已上传文件 2. 状态为「未开始」 | Excel步骤: 1. 在文件列表点击「开始」按钮（解析状态列） 2. 等待解析完成 | 预期: 解析完成；分块数列更新切片结果；状态变更为「成功」',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/chunks', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '触发解析/获取切片'}],
    },
    'RAG-022': {
        'title': '知识文件-单独配置解析策略',
        'module': '查看/创建知识库',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已上传文件 | Excel步骤: 1. 在文件列表点击「更多-切片方法」 2. 为该文件单独配置解析策略 3. 保存 | 预期: 单独配置生效；该文件按单独策略解析；不影响全局配置',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunking': {'strategy': 'naive'}}, 'desc': '单文件解析策略'}],
    },
    'RAG-023': {
        'title': '查看切片结果',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已完成解析的文件 | Excel步骤: 1. 点击文件名进入切片结果查看页 | 预期: 展示所有切片；含分块序号、内容、长度、来源',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/chunks', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '查看切片列表'}],
    },
    'RAG-024': {
        'title': '知识库检索测试',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已完成文件解析 | Excel步骤: 1. 在知识文件列表页点击「检索测试」 2. 配置相似度预置 3. 设置关键词权重 4. 设置 Top-K 5. 设置 rerank 模型 6. 在测试文本框输入查询问题 7. 点击检索 | 预期: 返回检索结果（按相似度排序）；含内容、来源、相似度',
        'steps': [{'method': 'POST', 'path': '/api/v1/searchbots/retrieval_test', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200], 'note_hint': '102=searchbots域凭证受限', 'params': {'kb_id': '{dataset_id}', 'question': '回归测试问题', 'top_k': 5}, 'desc': '检索测试(真实路由)'}],
    },
    'RAG-025': {
        'title': '知识库-编辑知识库名称',
        'module': '查看/创建知识库',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建知识库 | Excel步骤: 1. 进入知识库详情 2. 修改名称 3. 保存 | 预期: 名称更新成功；列表中显示新名称',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'name': '回归知识库-改名'}, 'desc': '编辑知识库'}],
    },
    'RAG-026': {
        'title': '知识库-删除知识库',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建知识库 | Excel步骤: 1. 在知识库列表选中知识库 2. 点击删除 3. 二次确认 4. 输入确认文字 | 预期: 知识库删除成功；列表中移除；删除记录可查询',
        'steps': [{'method': 'DELETE', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '删除知识库'}],
    },
    'RAG-027': {
        'title': '知识库-文件删除',
        'module': '查看/创建知识库',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识库有文件 | Excel步骤: 1. 在文件列表选择文件 2. 点击删除 3. 二次确认 | 预期: 文件删除成功；列表中移除；相关切片也删除',
        'steps': [{'method': 'DELETE', 'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '删除文件'}],
    },
    'RAG-028': {
        'title': '知识库-查看文件解析状态',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识库有多个文件 | Excel步骤: 1. 在文件列表查看解析状态列 | 预期: 显示每个文件的状态：未开始/解析中/成功/失败；失败显示原因',
        'steps': [{'method': 'GET', 'path': '/api/v1/datasets/{dataset_id}/documents/status', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200], 'note_hint': '102=文档归属校验(需真实文档ID)', 'desc': '查看解析状态(真实路由)'}],
    },
    'RAG-029': {
        'title': '知识库-检索测试中切换 Top-K',
        'module': '查看/创建知识库',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索测试页 | Excel步骤: 1. Top-K 设置为 5 检索 2. Top-K 设置为 10 检索 3. Top-K 设置为 20 检索 | 预期: 每次返回对应数量的检索结果',
        'steps': [{'method': 'POST', 'path': '/api/v1/searchbots/retrieval_test', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200], 'note_hint': '102=searchbots域凭证受限', 'params': {'kb_id': '{dataset_id}', 'question': 'test', 'top_k': 20}, 'desc': '大TopK检索(真实路由)'}],
    },
    'RAG-030': {
        'title': '切片方法-通用模式（基于分隔符+切片长度）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法配置页 | Excel步骤: 1. 切片模式选「通用」 2. 选择分隔符 3. 设置切片长度 4. 点击-开启按钮 | 预期: 切片按分隔符+长度组合；上传文档时按此策略处理',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'naive', 'parser_config': {'chunk_token_num': 512}}, 'desc': '通用切片配置'}],
    },
    'RAG-031': {
        'title': '切片方法-父子切片',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法配置页 | Excel步骤: 1. 切片模式选「父子切片」 2. 设置父块大小 3. 设置子块大小 4. 点击-开启按钮 | 预期: 父子切片生效；父块+子块两层结构；子块用于精确检索，父块用于补充上下文',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'parent_child', 'parser_config': {}}, 'desc': '父子切片配置'}],
    },
    'RAG-032': {
        'title': '切片方法-图文理解',
        'module': '切片与召回策略',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法配置页 2. 文档含图片 | Excel步骤: 1. 切片模式选「图文理解」 2. 启用图片识别 3. 保存 | 预期: 图片内容被识别并参与切片',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'picture', 'parser_config': {}}, 'desc': '图文理解切片配置'}],
    },
    'RAG-033': {
        'title': '召回策略-基于向量召回',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索策略页 | Excel步骤: 1. 关闭全文检索 2. 仅启用向量召回 3. 设置 Top-K 和相似度阈值 4. 保存 5. 在检索测试中查询 | 预期: 返回基于向量相似度的结果',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'search_method': 'vector'}}, 'desc': '纯向量召回'}],
    },
    'RAG-034': {
        'title': '召回策略-基于关键词召回',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索策略页 2. 切片方法已开启关键词提取 | Excel步骤: 1. 关闭向量检索 2. 仅启用关键词召回 3. 设置 Top-K 4. 保存 5. 查询 | 预期: 返回基于关键词匹配的结果',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'search_method': 'fulltext'}}, 'desc': '纯关键词召回'}],
    },
    'RAG-035': {
        'title': '召回策略-混合检索（向量+全文加权）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索策略页 | Excel步骤: 1. 开启向量检索和全文检索 2. 设置权重（如向量0.7/全文0.3） 3. 保存 4. 查询 | 预期: 返回混合加权结果',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'search_method': 'hybrid', 'weight': 0.7}}, 'desc': '混合检索配置'}],
    },
    'RAG-036': {
        'title': '召回策略-Rerank 模型',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索策略页 | Excel步骤: 1. 选择 rerank 模型 2. 保存 3. 查询 | 预期: 首次召回结果经 rerank 二次排序；返回更相关的结果',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'rerank_id': 'custom', 'rerank_model': '测试模型'}}, 'desc': 'Rerank配置'}],
    },
    'RAG-037': {
        'title': '召回策略-多路召回（分片内容路）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 检索策略页 | Excel步骤: 1. 开启多路召回 2. 开启分片内容路 3. 设置权重 4. 保存 | 预期: 检索时按分片内容路召回',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'multi_recall': {'content': True}}}, 'desc': '分片内容路配置'}],
    },
    'RAG-038': {
        'title': '召回策略-多路召回（分片标题路）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法选通用-按标题切分 2. 检索策略页开启多路召回 | Excel步骤: 1. 开启分片标题路 2. 设置权重 3. 保存 | 预期: 检索时按章节标题路召回',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'multi_recall': {'title': True}}}, 'desc': '分片标题路配置'}],
    },
    'RAG-039': {
        'title': '召回策略-多路召回（关键词路）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法开启关键词提取 2. 检索策略页开启多路召回 | Excel步骤: 1. 开启关键词路 2. 设置权重 3. 保存 | 预期: 检索时按关键词路召回',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'multi_recall': {'keyword': True}}}, 'desc': '关键词路配置'}],
    },
    'RAG-040': {
        'title': '召回策略-多路召回（问题路）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法开启问题提取 2. 检索策略页开启多路召回 | Excel步骤: 1. 开启问题路 2. 设置权重 3. 保存 | 预期: 检索时按问题路召回',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'retrieval_setting': {'multi_recall': {'question': True}}}, 'desc': '问题路配置'}],
    },
    'RAG-041': {
        'title': '召回策略-多路召回权重调整',
        'module': '切片与召回策略',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 多路召回已开启 | Excel步骤: 1. 调整各路权重 2. 保存 3. 多次查询对比 | 预期: 权重变化影响返回结果排序',
        'steps': [{'method': 'POST', 'path': '/api/v1/searchbots/retrieval_test', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200], 'note_hint': '102=searchbots域凭证受限', 'params': {'kb_id': '{dataset_id}', 'question': '权重对比', 'top_k': 10}, 'desc': '权重调整后检索'}],
    },
    'RAG-042': {
        'title': '切片方法-按标题切分（提取章节标题）',
        'module': '切片与召回策略',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法页 | Excel步骤: 1. 通用模式选「按标题切分」 2. 保存 | 预期: 切片时自动提取章节标题；分片标题 = 文件名+章节标题',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'naive', 'parser_config': {'delimiter': '\\n'}}, 'desc': '按标题切分配置'}],
    },
    'RAG-043': {
        'title': '切片方法-修改后重新解析',
        'module': '切片与召回策略',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已上传文件 2. 已完成解析 | Excel步骤: 1. 修改切片方法 2. 触发重新解析 | 预期: 按新切片策略重新解析；切片结果更新',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'chunk_method': 'naive'}, 'desc': '修改切片方法'}, {'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/chunks', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '触发重新解析'}],
    },
    'RAG-044': {
        'title': '创建标签库',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识库菜单 | Excel步骤: 1. 二级菜单选择「标签库」 2. 点击「创建标签库」 3. 填写标签库名称（如 处室） 4. 填写描述 5. 点击确定 | 预期: 标签库创建成功；出现在标签库列表',
        'steps': [{'method': 'POST', 'path': '/api/v1/tags', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200, 400], 'note_hint': '400=tag_base_id缺失/参数校验(环境)', 'params': {'name': '回归标签库-处室', 'description': '回归测试'}, 'desc': '创建标签库(真实接口)'}],
    },
    'RAG-045': {
        'title': '创建标签-单条创建',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建标签库「处室」 | Excel步骤: 1. 进入标签库详情 2. 点击「创建标签」 3. 填写标签名（如 财政部） 4. 填写关键词（如 财政部、财预） 5. 点击确定 | 预期: 标签创建成功；显示在标签库详情中',
        'steps': [{'method': 'POST', 'path': '/api/v1/tags', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200, 400], 'note_hint': '400=tag_base_id缺失/参数校验(环境)', 'params': {'name': '回归标签-财政部', 'keywords': ['财政部', '财预']}, 'desc': '创建标签(真实接口)'}],
    },
    'RAG-046': {
        'title': '创建标签-批量导入',
        'module': '配置标签',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'MIX',
        'note': '前置: 1. 已创建标签库 | Excel步骤: 1. 在标签库详情点击「批量导入标签」 2. 下载模板 3. 按模板填写标签数据 4. 上传 Excel 5. 确认导入 | 预期: 批量导入成功；多条标签同时创建',
        'steps': [{'method': 'POST', 'path': '/api/v1/tags', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200, 400], 'note_hint': '400=tag_base_id缺失/参数校验(环境)', 'params': {'names': ['标签A', '标签B', '标签C']}, 'desc': '批量创建标签(真实接口)'}],
    },
    'RAG-047': {
        'title': '知识库打标签',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建标签库和标签 2. 已有知识库 | Excel步骤: 1. 返回「知识库」列表 2. 点击知识库卡片下方空白区域 3. 在弹出页选择标签库 4. 选择标签库下的标签 5. 可选择多个标签库的多个标签 6. 点击确定 | 预期: 标签以键值对方式打在知识库上；卡片显示已选标签',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'tags': [{'name': '处室', 'value': '财政部'}]}, 'desc': '知识库打标签'}],
    },
    'RAG-048': {
        'title': '知识文件打标签',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识库已配置标签 | Excel步骤: 1. 进入知识库的知识文件列表 2. 在标签列为知识文件打标签 3. 选择标签库和标签 4. 确定 | 预期: 知识文件打标成功；标签列显示已选标签',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/tags', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'tags': ['回归标签']}, 'desc': '文件打标签'}],
    },
    'RAG-049': {
        'title': '知识片段打标签-手动打标',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已完成文件解析 2. 已有标签 | Excel步骤: 1. 选择知识文件进入切片结果页 2. 双击切片结果 3. 在编辑弹窗为知识片段打标签 4. 选择标签 5. 保存 | 预期: 切片打标成功；保存后该片段带有标签',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}/chunks/{chunk_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'tags': ['手动标签']}, 'desc': '片段打标签'}],
    },
    'RAG-050': {
        'title': '知识片段打标签-顶部编辑按钮',
        'module': '配置标签',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片结果查看页 | Excel步骤: 1. 点击右上角「编辑」按钮 2. 在编辑弹窗为多个切片批量打标签 3. 保存 | 预期: 批量打标成功',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/chunks/{chunk_id}/keywords', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'desc': '批量编辑片段'}],
    },
    'RAG-051': {
        'title': '知识片段自动打标-AI 打标',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 切片方法页 | Excel步骤: 1. 展开高级配置 2. 开启自动打标 3. 选择 AI 打标方式 4. 选择 1 个或多个标签库 5. 保存 | 预期: AI 自动打标启用；新解析的片段自动通过大模型匹配标签',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'parser_config': {'auto_question': True}}, 'desc': 'AI自动打标配置'}],
    },
    'RAG-052': {
        'title': '知识片段自动打标-关键词打标',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 标签已配置关键词 2. 切片方法页 | Excel步骤: 1. 展开高级配置 2. 开启自动打标 3. 选择关键词打标方式 4. 选择标签库 5. 保存 | 预期: 关键词打标启用；新解析的片段按关键词匹配自动打标',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'parser_config': {'auto_keywords': True}}, 'desc': '关键词自动打标配置'}],
    },
    'RAG-053': {
        'title': '标签库-查看已创建标签库列表',
        'module': '配置标签',
        'priority': 'P0',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建多个标签库 | Excel步骤: 1. 知识库菜单-标签库 2. 查看标签库列表 | 预期: 展示所有标签库；含名称、描述、标签数、创建时间',
        'steps': [{'method': 'GET', 'path': '/api/v1/tags?tag_base_id={tag_base_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200, 400], 'note_hint': '400=tag_base_id缺失/参数校验(环境)', 'desc': '标签库列表(真实接口)'}],
    },
    'RAG-054': {
        'title': '标签库-编辑标签',
        'module': '配置标签',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建标签 | Excel步骤: 1. 在标签库详情选择标签 2. 点击编辑 3. 修改名称/关键词 4. 保存 | 预期: 标签更新成功',
        'steps': [{'method': 'PUT', 'path': '/api/v1/tags/{tag_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200, 400], 'note_hint': '400=tag_base_id缺失/参数校验(环境)', 'params': {'name': '回归标签-改名', 'keywords': ['新关键词']}, 'desc': '编辑标签(真实接口)'}],
    },
    'RAG-055': {
        'title': '标签库-删除标签',
        'module': '配置标签',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 已创建标签 | Excel步骤: 1. 选择标签 2. 点击删除 3. 二次确认 | 预期: 标签删除成功；已打标的引用同步更新',
        'steps': [{'method': 'DELETE', 'path': '/api/v1/tags/{tag_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'expect_any': [200, 400], 'note_hint': '400=tag_base_id缺失/参数校验(环境)', 'desc': '删除标签(真实接口)'}],
    },
    'RAG-056': {
        'title': '知识库-编辑已打标签',
        'module': '配置标签',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识库已打标签 | Excel步骤: 1. 点击知识库卡片标签区域 2. 修改已选标签 3. 保存 | 预期: 标签更新成功',
        'steps': [{'method': 'PUT', 'path': '/api/v1/datasets/{dataset_id}', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'tags': [{'name': '处室', 'value': '新标签'}]}, 'desc': '编辑知识库标签'}],
    },
    'RAG-057': {
        'title': '知识文件-编辑已打标签',
        'module': '配置标签',
        'priority': 'P1',
        'platform': 'rag',
        'service': 'ragflow',
        'tag': 'API',
        'note': '前置: 1. 知识文件已打标签 | Excel步骤: 1. 在文件列表点击标签 2. 修改标签 3. 保存 | 预期: 标签更新成功',
        'steps': [{'method': 'POST', 'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/tags', 'base': 'https://rag.bosssoft.com.cn', 'expect': ['200'], 'expect_code': 200, 'params': {'tags': ['新标签']}, 'desc': '编辑文件标签'}],
    },
}

# 共 57 条 (Excel 主流程 57 条)  |  纯UI/无接口映射: 无