# -*- coding: utf-8 -*-
"""回归场景 - 智能体平台 (Agent-xxx, 74条)
数据来源: 智能体平台开发态-主流程回归测试用例.xlsx
由 tools/split_scenarios.py 从 regression_scenarios.py 拆分生成。
如需调整场景: 请修改本文件后执行 python tools/split_scenarios.py 重新拆分。
"""
from pathlib import Path

THIS_DIR = Path(__file__).parent
SCENARIOS = {
    'Agent-001': {'title': '首次登录自动加入公共工作空间',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '登录后获取当前工作空间'}]},
     'Agent-002': {'title': '搜索并申请加入已有工作空间',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '搜索工作空间列表'}]},
     'Agent-003': {'title': '工作空间管理员审批加入申请',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/members',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '管理员查看成员/待审批列表'},
                             {'method': 'POST',
                              'path': '/console/api/workspaces/current/members/owner-transfer-check',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '审批动作(探测)'}]},
     'Agent-004': {'title': '申请创建新工作空间',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/workspaces',
                              'expect': ['401', '200', '503'],
                              'expect_code': 201,
                              'desc': '提交创建申请(探测)'}]},
     'Agent-005': {'title': '切换工作空间',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取工作空间列表用于切换'},
                             {'method': 'POST',
                              'path': '/console/api/workspaces/switch',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '切换工作空间'}]},
     'Agent-006': {'title': '退出工作空间',
                   'module': '工作空间管理',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/members',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '退出前置: 查看成员/空间信息'}]},
     'Agent-007': {'title': '工作空间成员列表-查看成员',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/members',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '查看成员列表'}]},
     'Agent-008': {'title': '工作空间-移除成员（管理员）',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/members',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '移除成员前置: 成员列表'}]},
     'Agent-009': {'title': '工作空间-角色分配（管理员）',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/members',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '角色分配前置: 成员列表'}]},
     'Agent-010': {'title': '工作空间-工作空间信息查看',
                   'module': '工作空间管理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '查看工作空间详情'}]},
     'Agent-011': {'title': '从模板复制智能体到工作空间',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/explore/apps',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '浏览发现页模板列表'}]},
     'Agent-012': {'title': '从 0 创建智能体类型项目',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps',
                              'expect': ['401', '200', '503'],
                              'expect_code': 201,
                              'params': {'name': 'AI助手-回归', 'mode': 'agent-chat'},
                              'desc': '创建智能体项目'}]},
     'Agent-013': {'title': '从 0 创建对话流类型项目',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps',
                              'expect': ['401', '200', '503'],
                              'expect_code': 201,
                              'params': {'name': '业务流-回归', 'mode': 'advanced-chat'},
                              'desc': '创建对话流项目'}]},
     'Agent-014': {'title': '智能体-Prompt 编辑与模型选择',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/model-providers',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取可用模型提供商/模型列表'},
                             {'method': 'GET',
                              'path': '/console/api/workspaces/current/models/model-types/text-generation',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取文本生成模型列表'}]},
     'Agent-015': {'title': '智能体-添加变量到 Prompt',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '编辑前置: 应用列表'},
                             {'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取草稿配置(变量区)'}]},
     'Agent-016': {'title': '智能体-工具/插件挂载',
                   'module': '智能体设计',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/tools/workflow',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取可挂载工具列表'},
                             {'method': 'GET',
                              'path': '/console/api/workspaces/current/tool-providers',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取工具提供商'}]},
     'Agent-017': {'title': '智能体-Prompt 编辑完成并发布',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/publish',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '发布应用'}]},
     'Agent-018': {'title': '智能体-页面对话使用',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'note': '⚠️ 已知缺口: 该魔改版无 /workflows/task/{id} 查询路由(404), 待与开发确认',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'params': {'inputs': {}, 'response_mode': 'blocking'},
                              'desc': '运行对话/工作流'},
                             {'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/task/{task_id}',
                              'expect': ['404'],
                              'expect_code': 200,
                              'desc': '查询运行任务结果(魔改版无此路由)'}]},
     'Agent-019': {'title': '智能体-查看 API 接入文档',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/api-keys',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取 API Key(接入文档)'}]},
     'Agent-020': {'title': '智能体-更新版本（编辑后重新发布）',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/publish',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '重新发布新版本'}]},
     'Agent-021': {'title': '智能体-查看版本历史',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '查看配置(含版本信息)'}]},
     'Agent-022': {'title': '智能体-复制智能体',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/copy',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '复制应用'}]},
     'Agent-024': {'title': '智能体-删除智能体',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'DELETE',
                              'path': '/console/api/apps/{id}',
                              'expect': ['401', '200', '503'],
                              'expect_code': 204,
                              'desc': '删除应用'}]},
     'Agent-025': {'title': '智能体-导出配置',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/export',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '导出应用配置'}]},
     'Agent-026': {'title': '智能体-导入配置',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'note': '⚠️ 已知缺口: 该魔改版无 /apps/{id}/import 路由(404), 待与开发确认',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/import',
                              'expect': ['404'],
                              'expect_code': 200,
                              'desc': '导入应用配置(魔改版无此路由)'}]},
     'Agent-027': {'title': '智能体-切换大语言模型',
                   'module': '智能体设计',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/model-providers/{provider}/models',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取模型列表用于切换'}]},
     'Agent-028': {'title': '开始节点-添加并配置（文本输入）',
                   'module': '开始节点 Start',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '工作流草稿(开始节点配置)'}]},
     'Agent-029': {'title': '开始节点-添加段落输入字段',
                   'module': '开始节点 Start',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '工作流草稿(段落字段)'}]},
     'Agent-030': {'title': '开始节点-添加下拉选项字段',
                   'module': '开始节点 Start',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '工作流草稿(下拉字段)'}]},
     'Agent-031': {'title': '开始节点-添加数字+单文件+文件列表字段',
                   'module': '开始节点 Start',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '工作流草稿(多类型字段)'}]},
     'Agent-032': {'title': 'LLM 节点-选择模型与编写 prompt',
                   'module': 'LLM 节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行工作流触发LLM节点'}]},
     'Agent-033': {'title': 'LLM 节点-上下文变量引用',
                   'module': 'LLM 节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '草稿(上下文变量配置)'}]},
     'Agent-034': {'title': 'LLM 节点-记忆窗口配置',
                   'module': 'LLM 节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '多轮对话验证记忆窗口'}]},
     'Agent-035': {'title': 'LLM 节点-失败时重试配置',
                   'module': 'LLM 节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '草稿(重试配置)'}]},
     'Agent-036': {'title': 'LLM 节点-Jinja-2 模板渲染',
                   'module': 'LLM 节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'params': {'inputs': {'user_name': '回归测试'}},
                              'desc': '运行验证模板渲染'}]},
     'Agent-037': {'title': '知识检索-基础配置与查询',
                   'module': '知识检索节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/datasets/{dataset_id}/hit-testing',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'expect_any': [200, 400],
                              'note_hint': '400=向量库未就绪/参数受限(环境); 500=服务端缺陷',
                              'params': {'query': '回归测试', 'retrieval_model': {}},
                              'desc': '知识库检索(节点同源接口)'}]},
     'Agent-038': {'title': '知识检索-下游 LLM 节点关联',
                   'module': '知识检索节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets/{dataset_id}/documents',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '检索前置: 数据集文档'},
                             {'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行检索+LLM链路'}]},
     'Agent-039': {'title': '知识检索-输出 result 字段',
                   'module': '知识检索节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/datasets/{dataset_id}/hit-testing',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'expect_any': [200, 400],
                              'params': {'query': '测试', 'retrieval_model': {}},
                              'desc': '检索验证 result 字段完整性'}]},
     'Agent-040': {'title': '问题分类-多分类配置',
                   'module': '问题分类节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证分类路由'}]},
     'Agent-041': {'title': '问题分类-高级设置（指令/记忆/图片分析）',
                   'module': '问题分类节点',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '草稿(分类节点高级设置)'}]},
     'Agent-042': {'title': '问题分类-输出 class_name 字段',
                   'module': '问题分类节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证 class_name 输出'}]},
     'Agent-043': {'title': '条件分支-IF/ELSE 基础配置与运行',
                   'module': '条件分支节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'params': {'inputs': {'role': 'admin'}},
                              'desc': 'IF路径验证'},
                             {'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'params': {'inputs': {'role': 'user'}},
                              'desc': 'ELSE路径验证'}]},
     'Agent-044': {'title': '条件分支-包含/不包含判断',
                   'module': '条件分支节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'params': {'inputs': {'text': '紧急请求'}},
                              'desc': '包含匹配验证'}]},
     'Agent-045': {'title': '条件分支-开始是/结束是判断',
                   'module': '条件分支节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'params': {'inputs': {'cmd': 'get_status', 'file': 'report.pdf'}},
                              'desc': '前后缀匹配验证'}]},
     'Agent-046': {'title': '代码节点-Python 数据处理',
                   'module': '代码执行节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证代码节点'}]},
     'Agent-047': {'title': '代码节点-NodeJS 支持',
                   'module': '代码执行节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证JS代码节点'}]},
     'Agent-048': {'title': '代码节点-失败重试配置',
                   'module': '代码执行节点',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '草稿(重试配置)'}]},
     'Agent-049': {'title': '结束节点-基础配置',
                   'module': '结束节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证结束节点输出'}]},
     'Agent-050': {'title': '结束节点-多个输出变量',
                   'module': '结束节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证多输出'}]},
     'Agent-051': {'title': '节点异常处理-备用路径',
                   'module': '异常处理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证异常备用路径'}]},
     'Agent-052': {'title': '节点异常处理-抛出故障不中断',
                   'module': '异常处理',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证异常跳过'}]},
     'Agent-053': {'title': '工具节点-调用已注册插件',
                   'module': '工具节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/workspaces/current/tool-providers',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取已注册插件'},
                             {'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行工具节点'}]},
     'Agent-054': {'title': '工具节点-多插件串联',
                   'module': '工具节点',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行多工具串联'}]},
     'Agent-055': {'title': '循环节点-基础循环 3 次',
                   'module': '循环节点',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证循环执行'}]},
     'Agent-056': {'title': '循环节点-基于列表的循环',
                   'module': '循环节点',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行验证列表循环'}]},
     'Agent-057': {'title': '关联知识空间-管理员视角',
                   'module': '关联知识空间',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取知识库列表(关联前置)'}]},
     'Agent-058': {'title': '关联知识空间-快捷关联（管理员）',
                   'module': '关联知识空间',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '知识库列表(快捷关联)'}]},
     'Agent-059': {'title': '关联多个知识空间',
                   'module': '关联知识空间',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '多知识库列表'}]},
     'Agent-060': {'title': '取消关联知识空间',
                   'module': '关联知识空间',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets/{dataset_id}/use-check',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '取消关联前置检查'}]},
     'Agent-061': {'title': '访问知识库平台-跳转',
                   'module': '访问知识库平台',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'ragflow',
                   'tag': 'MIX',
                   'steps': [{'method': 'GET',
                              'path': '/api/v1/datasets',
                              'base': 'http://rag-func.ibosssoft.com.cn',
                              'expect': ['200'],
                              'expect_code': 200,
                              'desc': '跨平台跳转后可达'}]},
     'Agent-062': {'title': '访问知识库平台-SSO 单点登录',
                   'module': '访问知识库平台',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'cas',
                   'tag': 'MIX',
                   'steps': [{'method': 'GET',
                              'path': '/cas/login',
                              'base': 'http://cas-func.ibosssoft.com.cn',
                              'expect': ['200', '302'],
                              'expect_any': [200, 302],
                              'desc': 'CAS 登录页可达(200=页面正常,302=重定向)'}]},
     'Agent-063': {'title': '添加知识库-完整流程',
                   'module': '添加知识库',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/datasets',
                              'expect': ['401', '200', '503'],
                              'expect_code': 201,
                              'params': {'name': '回归知识库', 'indexing_technique': 'high_quality'},
                              'desc': '创建知识库'}]},
     'Agent-064': {'title': '添加知识库-召回设置配置',
                   'module': '添加知识库',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/datasets/{dataset_id}/hit-testing',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'expect_any': [200, 400],
                              'params': {'query': 'test', 'retrieval_model': {'top_k': 5}},
                              'desc': '召回设置验证(检索)'}]},
     'Agent-065': {'title': '添加知识库-查看已添加列表',
                   'module': '添加知识库',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '知识库列表'}]},
     'Agent-066': {'title': '知识检索-标签过滤（key-value Constant）',
                   'module': '标签过滤',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'ragflow',
                   'tag': 'API',
                   'note': '实测: 检索测试真实路由为 /api/v1/searchbots/retrieval_test (需kb_id)',
                   'steps': [{'method': 'POST',
                              'path': '/api/v1/searchbots/retrieval_test',
                              'base': 'http://rag-func.ibosssoft.com.cn',
                              'expect': ['200'],
                              'expect_code': 200,
                              'expect_any': [200],
                              'note_hint': '102=searchbots域凭证受限(需额外授权)',
                              'params': {'kb_id': '{dataset_id}',
                                         'question': '测试',
                                         'tags': [{'name': '处室', 'value': '财政部'}]},
                              'desc': '标签过滤检索(真实路由)'}]},
     'Agent-067': {'title': '知识检索-标签过滤-变量传入 Variable',
                   'module': '标签过滤',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'ragflow',
                   'tag': 'API',
                   'note': '实测: 检索测试真实路由为 /api/v1/searchbots/retrieval_test (需kb_id)',
                   'steps': [{'method': 'POST',
                              'path': '/api/v1/searchbots/retrieval_test',
                              'base': 'http://rag-func.ibosssoft.com.cn',
                              'expect': ['200'],
                              'expect_code': 200,
                              'expect_any': [200],
                              'note_hint': '102=searchbots域凭证受限',
                              'params': {'kb_id': '{dataset_id}', 'question': '测试', 'tags': []},
                              'desc': '变量标签过滤(真实路由)'}]},
     'Agent-068': {'title': '智能体编排-引用已添加知识库',
                   'module': '引用知识库',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets/{dataset_id}/documents',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '知识库文档(引用数据源)'},
                             {'method': 'POST',
                              'path': '/console/api/apps/{id}/workflows/run',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '运行检索+LLM链路'}]},
     'Agent-069': {'title': '页面访问智能体',
                   'module': '使用智能体',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'MIX',
                   'steps': [{'method': 'GET',
                              'path': '/explore/apps',
                              'expect': ['200'],
                              'expect_code': 200,
                              'desc': '智能体页面可达'}]},
     'Agent-070': {'title': '本地化部署-运行态环境启动',
                   'module': '使用智能体',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'UI',
                   'steps': []},
     'Agent-071': {'title': '本地化部署-运行态对话',
                   'module': '使用智能体',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'UI',
                   'steps': []},
     'Agent-072': {'title': '工作空间内智能体共享',
                   'module': '多租户协作',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '同空间应用列表'}]},
     'Agent-073': {'title': '智能体分享给同工作空间成员',
                   'module': '多租户协作',
                   'priority': 'P0',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'POST',
                              'path': '/console/api/apps/{id}/site',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '获取站点设置(分享前置, Dify标准为POST)'}]},
     'Agent-074': {'title': '智能体协作编辑（同工作空间）',
                   'module': '多租户协作',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/apps/{id}/workflows/draft',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '并发编辑读取草稿'}]},
     'Agent-075': {'title': '工作空间知识库共享',
                   'module': '多租户协作',
                   'priority': 'P1',
                   'platform': 'agent',
                   'service': 'dify',
                   'tag': 'API',
                   'steps': [{'method': 'GET',
                              'path': '/console/api/datasets',
                              'expect': ['401', '200', '503'],
                              'expect_code': 200,
                              'desc': '共享知识库列表'}]}
}
