# -*- coding: utf-8 -*-
"""回归场景 - 知识库平台 (RAG-xxx, 57条)
数据来源: 知识库平台-主流程回归测试用例.xlsx
由 tools/split_scenarios.py 从 regression_scenarios.py 拆分生成。
如需调整场景: 请修改本文件后执行 python tools/split_scenarios.py 重新拆分。
"""
from pathlib import Path

THIS_DIR = Path(__file__).parent
SCENARIOS = {
    'RAG-001': {'title': '首次登录自动加入公共工作空间',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/user/login',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'email': '${EMAIL}', 'password': '${PASSWORD}'},
                            'desc': '邮箱密码登录'}]},
     'RAG-002': {'title': '搜索工作空间',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '登录后工作空间数据可达'}]},
     'RAG-003': {'title': '申请加入已有工作空间',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'MIX',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '空间数据可达(申请入口)'}]},
     'RAG-004': {'title': '工作空间管理员审批加入申请',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'MIX',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '成员数据可达(审批前置)'}]},
     'RAG-005': {'title': '切换工作空间',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '切换后数据可达'}]},
     'RAG-006': {'title': '查看当前工作空间成员',
                 'module': '加入工作空间',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'MIX',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '成员列表(同空间数据)'}]},
     'RAG-007': {'title': '查看工作空间信息',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'MIX',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '空间信息数据可达'}]},
     'RAG-008': {'title': '工作空间-申请创建新工作空间',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'UI',
                 'steps': []},
     'RAG-009': {'title': '工作空间-退出工作空间',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'MIX',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '退出前数据可达'}]},
     'RAG-010': {'title': '工作空间-修改个人信息',
                 'module': '加入工作空间',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'UI',
                 'steps': []},
     'RAG-011': {'title': '查看工作空间知识库列表',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '知识库列表'}]},
     'RAG-012': {'title': '创建知识库-基础创建',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'name': '回归知识库', 'embedding_model': '${EMBEDDING_MODEL}'},
                            'desc': '创建知识库'}]},
     'RAG-013': {'title': '配置知识库-切片方法',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'naive'},
                            'desc': '配置切片方法'}]},
     'RAG-014': {'title': '配置知识库-检索策略（基础）',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'top_k': 10,
                                                             'threshold': 0.2,
                                                             'rerank_id': 'default'}},
                            'desc': '配置检索策略'}]},
     'RAG-015': {'title': '配置知识库-多路召回策略',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'search_method': 'hybrid'}},
                            'desc': '多路召回配置'}]},
     'RAG-016': {'title': '配置知识库-切片方法高级配置',
                 'module': '查看/创建知识库',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'naive', 'parser_config': {'auto_keywords': True}},
                            'desc': '高级切片配置'}]},
     'RAG-017': {'title': '配置知识库-QA 模式',
                 'module': '查看/创建知识库',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'qa'},
                            'desc': 'QA切片模式配置'}]},
     'RAG-018': {'title': '上传知识文件-单文件拖拽',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'file_type': 'txt', 'file': '回归测试文件.txt'},
                            'desc': '上传单文件'}]},
     'RAG-019': {'title': '上传知识文件-多文件批量上传',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'files': ['回归测试文件1.txt', '回归测试文件2.txt']},
                            'desc': '批量上传'}]},
     'RAG-020': {'title': '上传支持格式验证（word/pdf/excel/ppt/txt）',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'files': ['test.docx', 'test.pdf', 'test.xlsx', 'test.pptx', 'test.txt']},
                            'desc': '多格式上传'}]},
     'RAG-021': {'title': '知识文件-触发解析',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/chunks',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '触发解析/获取切片'}]},
     'RAG-022': {'title': '知识文件-单独配置解析策略',
                 'module': '查看/创建知识库',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunking': {'strategy': 'naive'}},
                            'desc': '单文件解析策略'}]},
     'RAG-023': {'title': '查看切片结果',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/chunks',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '查看切片列表'}]},
     'RAG-024': {'title': '知识库检索测试',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 检索测试真实路由为 /api/v1/searchbots/retrieval_test (需kb_id)',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/searchbots/retrieval_test',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200],
                            'note_hint': '102=searchbots域凭证受限',
                            'params': {'kb_id': '{dataset_id}', 'question': '回归测试问题', 'top_k': 5},
                            'desc': '检索测试(真实路由)'}]},
     'RAG-025': {'title': '知识库-编辑知识库名称',
                 'module': '查看/创建知识库',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'name': '回归知识库-改名'},
                            'desc': '编辑知识库'}]},
     'RAG-026': {'title': '知识库-删除知识库',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'DELETE',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '删除知识库'}]},
     'RAG-027': {'title': '知识库-文件删除',
                 'module': '查看/创建知识库',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'DELETE',
                            'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '删除文件'}]},
     'RAG-028': {'title': '知识库-查看文件解析状态',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: /documents/{doc_id}/status 为404伪路由; 真实状态查询为 /documents/status',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/datasets/{dataset_id}/documents/status',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200],
                            'note_hint': '102=文档归属校验(需真实文档ID)',
                            'desc': '查看解析状态(真实路由)'}]},
     'RAG-029': {'title': '知识库-检索测试中切换 Top-K',
                 'module': '查看/创建知识库',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 检索测试真实路由为 /api/v1/searchbots/retrieval_test (需kb_id)',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/searchbots/retrieval_test',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200],
                            'note_hint': '102=searchbots域凭证受限',
                            'params': {'kb_id': '{dataset_id}', 'question': 'test', 'top_k': 20},
                            'desc': '大TopK检索(真实路由)'}]},
     'RAG-030': {'title': '切片方法-通用模式（基于分隔符+切片长度）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'naive', 'parser_config': {'chunk_token_num': 512}},
                            'desc': '通用切片配置'}]},
     'RAG-031': {'title': '切片方法-父子切片',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'parent_child', 'parser_config': {}},
                            'desc': '父子切片配置'}]},
     'RAG-032': {'title': '切片方法-图文理解',
                 'module': '切片与召回策略',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'picture', 'parser_config': {}},
                            'desc': '图文理解切片配置'}]},
     'RAG-033': {'title': '召回策略-基于向量召回',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'search_method': 'vector'}},
                            'desc': '纯向量召回'}]},
     'RAG-034': {'title': '召回策略-基于关键词召回',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'search_method': 'fulltext'}},
                            'desc': '纯关键词召回'}]},
     'RAG-035': {'title': '召回策略-混合检索（向量+全文加权）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'search_method': 'hybrid', 'weight': 0.7}},
                            'desc': '混合检索配置'}]},
     'RAG-036': {'title': '召回策略-Rerank 模型',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'rerank_id': 'custom', 'rerank_model': '测试模型'}},
                            'desc': 'Rerank配置'}]},
     'RAG-037': {'title': '召回策略-多路召回（分片内容路）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'multi_recall': {'content': True}}},
                            'desc': '分片内容路配置'}]},
     'RAG-038': {'title': '召回策略-多路召回（分片标题路）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'multi_recall': {'title': True}}},
                            'desc': '分片标题路配置'}]},
     'RAG-039': {'title': '召回策略-多路召回（关键词路）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'multi_recall': {'keyword': True}}},
                            'desc': '关键词路配置'}]},
     'RAG-040': {'title': '召回策略-多路召回（问题路）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'retrieval_setting': {'multi_recall': {'question': True}}},
                            'desc': '问题路配置'}]},
     'RAG-041': {'title': '召回策略-多路召回权重调整',
                 'module': '切片与召回策略',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 检索测试真实路由为 /api/v1/searchbots/retrieval_test (需kb_id)',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/searchbots/retrieval_test',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200],
                            'note_hint': '102=searchbots域凭证受限',
                            'params': {'kb_id': '{dataset_id}', 'question': '权重对比', 'top_k': 10},
                            'desc': '权重调整后检索'}]},
     'RAG-042': {'title': '切片方法-按标题切分（提取章节标题）',
                 'module': '切片与召回策略',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'naive', 'parser_config': {'delimiter': '\\n'}},
                            'desc': '按标题切分配置'}]},
     'RAG-043': {'title': '切片方法-修改后重新解析',
                 'module': '切片与召回策略',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'chunk_method': 'naive'},
                            'desc': '修改切片方法'},
                           {'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/chunks',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '触发重新解析'}]},
     'RAG-044': {'title': '创建标签库',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: /api/v1/datasets/tags 为405伪路由; 真实标签接口为 /api/v1/tags (需tag_base_id)',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/tags',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200, 400],
                            'note_hint': '400=tag_base_id缺失/参数校验(环境)',
                            'params': {'name': '回归标签库-处室', 'description': '回归测试'},
                            'desc': '创建标签库(真实接口)'}]},
     'RAG-045': {'title': '创建标签-单条创建',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 真实标签接口为 /api/v1/tags',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/tags',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200, 400],
                            'note_hint': '400=tag_base_id缺失/参数校验(环境)',
                            'params': {'name': '回归标签-财政部', 'keywords': ['财政部', '财预']},
                            'desc': '创建标签(真实接口)'}]},
     'RAG-046': {'title': '创建标签-批量导入',
                 'module': '配置标签',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'MIX',
                 'note': '实测: 真实标签接口为 /api/v1/tags',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/tags',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200, 400],
                            'note_hint': '400=tag_base_id缺失/参数校验(环境)',
                            'params': {'names': ['标签A', '标签B', '标签C']},
                            'desc': '批量创建标签(真实接口)'}]},
     'RAG-047': {'title': '知识库打标签',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'tags': [{'name': '处室', 'value': '财政部'}]},
                            'desc': '知识库打标签'}]},
     'RAG-048': {'title': '知识文件打标签',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/tags',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'tags': ['回归标签']},
                            'desc': '文件打标签'}]},
     'RAG-049': {'title': '知识片段打标签-手动打标',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}/chunks/{chunk_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'tags': ['手动标签']},
                            'desc': '片段打标签'}]},
     'RAG-050': {'title': '知识片段打标签-顶部编辑按钮',
                 'module': '配置标签',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/chunks/{chunk_id}/keywords',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'desc': '批量编辑片段'}]},
     'RAG-051': {'title': '知识片段自动打标-AI 打标',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'parser_config': {'auto_question': True}},
                            'desc': 'AI自动打标配置'}]},
     'RAG-052': {'title': '知识片段自动打标-关键词打标',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'parser_config': {'auto_keywords': True}},
                            'desc': '关键词自动打标配置'}]},
     'RAG-053': {'title': '标签库-查看已创建标签库列表',
                 'module': '配置标签',
                 'priority': 'P0',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 真实标签接口为 /api/v1/tags?tag_base_id=xxx; datasets/tags为405伪路由',
                 'steps': [{'method': 'GET',
                            'path': '/api/v1/tags?tag_base_id={tag_base_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200, 400],
                            'note_hint': '400=tag_base_id缺失/参数校验(环境)',
                            'desc': '标签库列表(真实接口)'}]},
     'RAG-054': {'title': '标签库-编辑标签',
                 'module': '配置标签',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 真实标签接口为 /api/v1/tags (含tag标识参数)',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/tags/{tag_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200, 400],
                            'note_hint': '400=tag_base_id缺失/参数校验(环境)',
                            'params': {'name': '回归标签-改名', 'keywords': ['新关键词']},
                            'desc': '编辑标签(真实接口)'}]},
     'RAG-055': {'title': '标签库-删除标签',
                 'module': '配置标签',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'note': '实测: 真实标签接口为 /api/v1/tags (含tag标识参数)',
                 'steps': [{'method': 'DELETE',
                            'path': '/api/v1/tags/{tag_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'expect_any': [200, 400],
                            'note_hint': '400=tag_base_id缺失/参数校验(环境)',
                            'desc': '删除标签(真实接口)'}]},
     'RAG-056': {'title': '知识库-编辑已打标签',
                 'module': '配置标签',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'PUT',
                            'path': '/api/v1/datasets/{dataset_id}',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'tags': [{'name': '处室', 'value': '新标签'}]},
                            'desc': '编辑知识库标签'}]},
     'RAG-057': {'title': '知识文件-编辑已打标签',
                 'module': '配置标签',
                 'priority': 'P1',
                 'platform': 'rag',
                 'service': 'ragflow',
                 'tag': 'API',
                 'steps': [{'method': 'POST',
                            'path': '/api/v1/datasets/{dataset_id}/documents/{document_id}/tags',
                            'base': 'https://rag.bosssoft.com.cn',
                            'expect': ['200'],
                            'expect_code': 200,
                            'params': {'tags': ['新标签']},
                            'desc': '编辑文件标签'}]}
}
